default_stages:
  - "commit"

repos:
  - repo: "https://github.com/compilerla/conventional-pre-commit"
    rev: "v1.3.0"
    hooks:
      - id: "conventional-pre-commit"
        stages:
          - "commit-msg"

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.3.0"
    hooks:
      - id: "check-toml"
      - id: "check-yaml"
      - id: "end-of-file-fixer"
      - id: "mixed-line-ending"
        args:
          - "--fix=lf"
      - id: "trailing-whitespace"

  - repo: "https://github.com/doublify/pre-commit-rust"
    rev: "v1.0"
    hooks:
      - id: "fmt"
      - id: "cargo-check"
      - id: "clippy"
